export const menuItemsData = [
    {
      id: 1,
      name: 'Burger',
      info: 'Spicy with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://res.cloudinary.com/jllacson/image/upload/v1640721244/sampleShop/bigBurger_vflr8d.png',
    },
    {
      id: 2,
      name: 'Summer Asian Slaw',
      info: 'Spicy with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://res.cloudinary.com/jllacson/image/upload/v1640723382/sampleShop/bowl1_gyk3aw.png',
    },
    {
      id: 3,
      name: 'Mediterranean  Salad',
      info: 'Spicy with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://res.cloudinary.com/jllacson/image/upload/v1640723382/sampleShop/bowl2_jn1wzr.png',
    },
    {
      id: 4,
      name: 'White Sauce Pasta',
      info: 'Spicy with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://res.cloudinary.com/jllacson/image/upload/v1640723381/sampleShop/bowl3_kschov.png',
    },
    {
      id: 5,
      name: 'Butterfly Pasta',
      info: 'Spicy with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://res.cloudinary.com/jllacson/image/upload/v1640723382/sampleShop/bowl4_ms9q2i.png',
    },
    {
      id: 6,
      name: 'Tooty Fruity Bowl',
      info: 'Spicy with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://res.cloudinary.com/jllacson/image/upload/v1640723382/sampleShop/fruits_mqqrpn.png',
    },
    {
      id: 7,
      name: 'Granola Cereal Bowl',
      info: 'Spicy with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://res.cloudinary.com/jllacson/image/upload/v1640723385/sampleShop/granola_cereal_bowl_efpdne.png',
    },
    {
      id: 8,
      name: 'Palm Bowl',
      info: 'Spicy with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://res.cloudinary.com/jllacson/image/upload/v1640723383/sampleShop/kisspng-aa-na-tigela-smoothie-aa-palm-bowl-apple-j-goji-berry-5b306ffe7baf07.9992682215299010545066_rgxlxm.png',
    },
    {
      id: 9,
      name: 'Tigela Smoothie',
      info: 'Spicy with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://res.cloudinary.com/jllacson/image/upload/v1640723382/sampleShop/kisspng-aa-na-tigela-smoothie-breakfast-juice-health-s-acai-bowl-5b11d2604db908.6695630315278946243184_lory0v.png',
    },
    {
      id: 10,
      name: 'Breakfast Cereal',
      info: 'Spicy with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://res.cloudinary.com/jllacson/image/upload/v1640723386/sampleShop/kisspng-breakfast-cereal-pizza-muesli-meze-vegetarian-cuis-granola-5ac48d852aeb69.1891892315228307251758_i4cpet.png',
    },
    {
      id: 11,
      name: 'Cuisine of Hawaii',
      info: 'Spicy with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://res.cloudinary.com/jllacson/image/upload/v1640723385/sampleShop/kisspng-cuisine-of-hawaii-l-l-hawaiian-barbecue-shrimp-gam-frozen-chicken-5b1e62f3a9e035.2766282415287180676958_rooirl.png',
    },
    {
      id: 12,
      name: 'Fried Chicken',
      info: 'Spicy with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://res.cloudinary.com/jllacson/image/upload/v1640723383/sampleShop/kisspng-fried-chicken-lemon-chicken-chicken-meat-fine-dining-chicken-meat-5a940a1b75aa22.821205431519651355482_pzaysj.png',
    },
    {
      id: 13,
      name: 'Greek Salad',
      info: 'Spicy with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://res.cloudinary.com/jllacson/image/upload/v1640723386/sampleShop/kisspng-greek-salad-fruit-salad-spinach-salad-muesli-vegetable-salad-5a96f429ce9af3.7299622115198423458463_msls7f.png',
    },
    {
      id: 14,
      name: 'Hamburger',
      info: 'Spicy with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://res.cloudinary.com/jllacson/image/upload/v1640723384/sampleShop/kisspng-hamburger-street-food-seafood-fast-food-delicious-food-5a75083cceaf41.2676743415176192608466_p8pmkm.png',
    },
    {
      id: 15,
      name: 'Israeli Salad',
      info: 'Spicy with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://res.cloudinary.com/jllacson/image/upload/v1640723385/sampleShop/kisspng-israeli-salad-european-cuisine_jvutu3.png',
    },
    {
      id: 16,
      name: 'Pizza Pasta',
      info: 'Spicy with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://res.cloudinary.com/jllacson/image/upload/v1640723384/sampleShop/kisspng-italian-cuisine-pizza-pasta-food-plate-healthy-food-5abb864701e2b7.3892346415222390470077_scosdh.png',
    },
    {
      id: 17,
      name: 'Pizza',
      info: 'Spicy with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://res.cloudinary.com/jllacson/image/upload/v1640723386/sampleShop/pizza_cuvk2j.png',
    },
  ];